# Generated by Django 4.1.5 on 2023-01-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_category_comments_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.CharField(max_length=1000),
        ),
    ]
