# Generated by Django 4.1.5 on 2023-01-09 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ManyToManyField(blank=True, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
