# Generated by Django 4.1.5 on 2023-01-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_bid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
